# Generated by Django 5.2.4 on 2025-08-10 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_managers_remove_user_nom_user_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='filiere',
            field=models.CharField(choices=[('Data', 'DATA'), ('Dev-Web', 'Dev-Web'), ('Ref-Dig', 'Ref-Dig'), ('Aws', 'Aws'), ('Hackeuuse', 'Hackeuse')], max_length=20),
        ),
    ]
