# Generated by Django 5.2.4 on 2025-08-22 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_filiere'),
        ('users', '0003_alter_user_filiere1'),
    ]

    operations = [
    ]
