# Generated by Django 5.2.4 on 2025-08-26 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plannings', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='planning',
            unique_together={('period', 'jour')},
        ),
        migrations.AddConstraint(
            model_name='planning',
            constraint=models.UniqueConstraint(fields=('period', 'jour'), name='unique_jour_per_period'),
        ),
    ]
